name: tripmate_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  http: ^1.5.0
  carousel_slider: ^5.1.1
  cloud_firestore: ^6.1.0
  firebase_core: ^4.3.0
  google_maps_flutter: ^2.14.0
  flutter_polyline_points: ^3.1.0
  firebase_auth: ^6.1.3
  
  

flutter:
  uses-material-design: true
  assets:
    - assets/travel.png